name: "CI/CD"
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6
      - uses: cachix/cachix-action@v3
        with:
          name: xe
      - run: |
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-env -if ./nix/dhall-yaml.nix kubectl doctl
          ./nix/deploy.sh
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          DOCKER_USERNAME: "xena"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
